name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-24.04

    steps:
      - name: Generate GH Token
        id: generate-token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        with:
          app-id: ${{ secrets.GH_SYNC_APP_ID }}
          private-key: ${{ secrets.GH_SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ github.repository }}

      - uses: tgymnich/fork-sync@e905b254d56ebb367514cd05fa96bf7516bd2a5a # v2.0.10
        with:
          owner: cilium
          base: main
          head: main
          token: ${{ steps.generate-token.outputs.token }}
